// src/Galeria.js

export const galeriaDb = [
  { id: 1, imagenUrl: '/images/Pasteles/brownies_Halloween.webp', alt: 'Brownies temáticos de Halloween' , categoria: 'brownies'},
  { id: 2, imagenUrl: '/images/Pasteles/Cupcakes_flores.webp', alt: 'Cupcakes decorados con flores', categoria: 'cupcakes' },
  { id: 3, imagenUrl: '/images/Pasteles/Cupcakes_navideños.webp', alt: 'Cupcakes con decoración navideña', categoria: 'cupcakes' },
  { id: 4, imagenUrl: '/images/Pasteles/cupcakesFotball.webp', alt: 'Cupcakes temáticos de fútbol' , categoria: 'cupcakes'},
  { id: 5, imagenUrl: '/images/Pasteles/Galletas_animalitos.webp', alt: 'Galletas decoradas de animalitos', categoria: 'galletas'},
  { id: 6, imagenUrl: '/images/Pasteles/Galletas_Conejo.webp', alt: 'Galletas en forma de conejo' , categoria: 'galletas'},
  { id: 7, imagenUrl: '/images/Pasteles/Galletas_hombre.webp', alt: 'Galletas decoradas' , categoria: 'galletas'},
  { id: 8, imagenUrl: '/images/Pasteles/Galletas_pez.webp', alt: 'Galletas en forma de pez' , categoria: 'galletas'},
  { id: 9, imagenUrl: '/images/Pasteles/Mini_brownies.webp', alt: 'Mini brownies decorados' , categoria: 'brownies'},
  { id: 10, imagenUrl: '/images/Pasteles/MiniPays.webp', alt: 'Mini pays surtidos' , categoria: 'pay'},
  { id: 11, imagenUrl: '/images/Pasteles/Pastel_actriz.webp', alt: 'Pastel personalizado temática actriz', categoria: 'pasteles'},
  { id: 12, imagenUrl: '/images/Pasteles/Pastel_anime.webp', alt: 'Pastel con temática de anime' , categoria: 'pasteles'},
  { id: 13, imagenUrl: '/images/Pasteles/Pastel_bolaBeisbol.webp', alt: 'Pastel en forma de bola de béisbol' , categoria: 'pasteles'},
  { id: 14, imagenUrl: '/images/Pasteles/Pastel_cars_chiquito.webp', alt: 'Pastel pequeño de Cars' , categoria: 'pasteles'},
  { id: 15, imagenUrl: '/images/Pasteles/pastel_cars.webp', alt: 'Pastel temático de Cars' , categoria: 'pasteles'},
  { id: 16, imagenUrl: '/images/Pasteles/Pastel_corazon_rosa.webp', alt: 'Pastel en forma de corazón color rosa' , categoria: 'pasteles'},
  { id: 17, imagenUrl: '/images/Pasteles/Pastel_Dancing_queen.webp', alt: 'Pastel temática Dancing Queen' , categoria: 'pasteles'},
  { id: 18, imagenUrl: '/images/Pasteles/Pastel_Golden.webp', alt: 'Pastel elegante con toques dorados' , categoria: 'pasteles'},
  { id: 19, imagenUrl: '/images/Pasteles/Pastel_Manzanas.webp', alt: 'Pastel decorado de manzanas' , categoria: 'pasteles'},
  { id: 20, imagenUrl: '/images/Pasteles/Pastel_Matilda.webp', alt: 'Pastel de chocolate estilo Matilda' , categoria: 'pasteles'},
  { id: 21, imagenUrl: '/images/Pasteles/Pastel_monstruo.webp', alt: 'Pastel divertido de monstruo' , categoria: 'pasteles'},
  { id: 22, imagenUrl: '/images/Pasteles/pastel_OneDirection.webp', alt: 'Pastel de One Direction' , categoria: 'pasteles'},
  { id: 23, imagenUrl: '/images/Pasteles/Pastel_papa.webp', alt: 'Pastel especial para papá' , categoria: 'pasteles'},
  { id: 24, imagenUrl: '/images/Pasteles/Pastel_Sabrina.webp', alt: 'Pastel temática Sabrina' , categoria: 'pasteles'},
  { id: 25, imagenUrl: '/images/Pasteles/Pastel_Tarea.webp', alt: 'Pastel divertido de tarea' , categoria: 'pasteles'},
  { id: 26, imagenUrl: '/images/Pasteles/Pastel_Volver_Al_Futuro.webp', alt: 'Pastel de Volver al Futuro' , categoria: 'pasteles'},
  { id: 27, imagenUrl: '/images/Pasteles/PastelHB_azul.webp', alt: 'Pastel de cumpleaños en tonos azules' , categoria: 'pasteles'},
  { id: 28, imagenUrl: '/images/Pasteles/PastelHB_BobEsponja.webp', alt: 'Pastel de cumpleaños de Bob Esponja' , categoria: 'pasteles'},
  { id: 29, imagenUrl: '/images/Pasteles/PastelHB_chiquito.webp', alt: 'Pastel de cumpleaños pequeño' , categoria: 'pasteles'},
  { id: 30, imagenUrl: '/images/Pasteles/PastelHB_Felipe.webp', alt: 'Pastel de cumpleaños para Felipe' , categoria: 'pasteles'},
  { id: 31, imagenUrl: '/images/Pasteles/PastelHB_hanna.webp', alt: 'Pastel de cumpleaños para Hanna' , categoria: 'pasteles'},
  { id: 32, imagenUrl: '/images/Pasteles/PastelHB_negro.webp', alt: 'Pastel de cumpleaños elegante en color negro' , categoria: 'pasteles'},
  { id: 33, imagenUrl: '/images/Pasteles/PastelRojo_corazon.webp', alt: 'Pastel rojo en forma de corazón' , categoria: 'pasteles'},
  { id: 34, imagenUrl: '/images/Pasteles/personalizado_Rapunzel.webp', alt: 'Pastel personalizado de Rapunzel' , categoria: 'pasteles'}
];